import { getIcon } from "../plugin/icon-registry"
// Side-effect import: registers all built-in Lucide icon names in the registry
import "../plugin/builtin-icons"

import { splitProps, type ComponentProps } from "solid-js"
import { Dynamic } from "solid-js/web"
import {
  Activity,
  AlignRight,
  Archive,
  ArchiveRestore,
  ArrowDownFromLine,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  BadgeAlert,
  BadgeCheck,
  BadgeX,
  Ban,
  Binoculars,
  BookDown,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Boxes,
  Braces,
  Brain,
  Bug,
  Building2,
  Cable,
  CalendarClock,
  CalendarDays,
  ChartPie,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleDashed,
  CircleGauge,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleX,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  ClipboardX,
  Clock,
  CloudUpload,
  Code,
  Compass,
  ContactRound,
  Copy,
  CornerDownLeft,
  Cpu,
  Crown,
  Crosshair,
  Database,
  Diamond,
  Diff,
  Disc,
  Download,
  DownloadCloud,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileArchive,
  FileCheck2,
  FilePen,
  FileSearch,
  FileTerminal,
  FileText,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderCog,
  FolderInput,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Funnel,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  Github,
  GitMerge,
  Glasses,
  Globe,
  Gpu,
  GraduationCap,
  Grip,
  GripVertical,
  Hand,
  HardDrive,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Hourglass,
  Image,
  Inbox,
  Info,
  Kanban,
  KeyRound,
  Languages,
  Layers,
  LayoutGrid,
  Lightbulb,
  List,
  ListChecks,
  ListCollapse,
  ListFilter,
  ListTodo,
  LoaderCircle,
  LockKeyhole,
  LogIn,
  LogOut,
  Mail,
  MailSearch,
  Map,
  Maximize,
  Megaphone,
  MemoryStick,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareMore,
  Mic,
  Microscope,
  Minimize,
  Minimize2,
  Minus,
  Monitor,
  MonitorDot,
  Moon,
  MousePointer2,
  MousePointerClick,
  Network,
  NotebookPen,
  OctagonAlert,
  Orbit,
  Package,
  Palette,
  PanelBottom,
  PanelBottomClose,
  PanelBottomDashed,
  PanelBottomOpen,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pen,
  Pencil,
  PenLine,
  Pin,
  PinOff,
  Plus,
  PlugZap,
  Quote,
  Radar,
  Redo2,
  RefreshCcw,
  RefreshCcwDot,
  Regex,
  Repeat,
  Rocket,
  RotateCcw,
  RotateCw,
  Route,
  Satellite,
  Scale,
  Scan,
  ScanEye,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Share,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Shrink,
  Sigma,
  Signal,
  SlidersHorizontal,
  Sparkles,
  Split,
  Spline,
  Square,
  SquareCheck,
  SquarePen,
  SquarePlay,
  SquareX,
  Stamp,
  Star,
  StarHalf,
  StarOff,
  Stethoscope,
  Sun,
  Table,
  Tag,
  Telescope,
  Terminal,
  TextSelect,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  UndoDot,
  Upload,
  User,
  UserPlus,
  UserRoundPen,
  Users,
  Waypoints,
  Workflow,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-solid"

const icons = {
  activity: Activity,
  "alert-triangle": TriangleAlert,
  "align-right": AlignRight,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-down-from-line": ArrowDownFromLine,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  "audio-lines": AudioLines,
  "badge-alert": BadgeAlert,
  "badge-check": BadgeCheck,
  "badge-x": BadgeX,
  ban: Ban,
  binoculars: Binoculars,
  "book-down": BookDown,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  bookmark: Bookmark,
  languages: Languages,
  bot: Bot,
  boxes: Boxes,
  braces: Braces,
  brain: Brain,
  bug: Bug,
  "building-2": Building2,
  cable: Cable,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  kanban: Kanban,
  "chart-pie": ChartPie,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-right": ChevronsRight,
  circle: Circle,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-gauge": CircleGauge,
  "circle-pause": CirclePause,
  "circle-play": CirclePlay,
  "circle-plus": CirclePlus,
  "circle-stop": CircleStop,
  "circle-x": CircleX,
  "circuit-board": CircuitBoard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clipboard-x": ClipboardX,
  clock: Clock,
  "cloud-upload": CloudUpload,
  code: Code,
  compass: Compass,
  "contact-round": ContactRound,
  copy: Copy,
  "corner-down-left": CornerDownLeft,
  cpu: Cpu,
  crosshair: Crosshair,
  crown: Crown,
  database: Database,
  diamond: Diamond,
  diff: Diff,
  disc: Disc,
  download: Download,
  "download-cloud": DownloadCloud,
  ellipsis: Ellipsis,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  "file-archive": FileArchive,
  "file-check-2": FileCheck2,
  "file-pen": FilePen,
  "file-terminal": FileTerminal,
  "file-text": FileText,
  fingerprint: Fingerprint,
  flag: Flag,
  flame: Flame,
  "flask-conical": FlaskConical,
  folder: Folder,
  "folder-cog": FolderCog,
  "folder-input": FolderInput,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "folder-tree": FolderTree,
  funnel: Funnel,
  gauge: Gauge,
  "git-branch": GitBranch,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-fork": GitFork,
  "git-merge": GitMerge,
  github: Github,
  glasses: Glasses,
  globe: Globe,
  gpu: Gpu,
  "graduation-cap": GraduationCap,
  grip: Grip,
  "grip-vertical": GripVertical,
  hand: Hand,
  "hard-drive": HardDrive,
  "heart-pulse": HeartPulse,
  "help-circle": HelpCircle,
  history: History,
  home: Home,
  hourglass: Hourglass,
  image: Image,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  layers: Layers,
  "layout-grid": LayoutGrid,
  lightbulb: Lightbulb,
  list: List,
  "list-checks": ListChecks,
  "list-collapse": ListCollapse,
  "list-filter": ListFilter,
  "list-todo": ListTodo,
  "loader-circle": LoaderCircle,
  "lock-keyhole": LockKeyhole,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "mail-search": MailSearch,
  map: Map,
  maximize: Maximize,
  megaphone: Megaphone,
  "memory-stick": MemoryStick,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "message-square-more": MessageSquareMore,
  mic: Mic,
  microscope: Microscope,
  minimize: Minimize,
  "minimize-2": Minimize2,
  minus: Minus,
  monitor: Monitor,
  "monitor-dot": MonitorDot,
  moon: Moon,
  "mouse-pointer-2": MousePointer2,
  "mouse-pointer-click": MousePointerClick,
  network: Network,
  "notebook-pen": NotebookPen,
  "octagon-alert": OctagonAlert,
  orbit: Orbit,
  package: Package,
  palette: Palette,
  "panel-bottom": PanelBottom,
  "panel-bottom-close": PanelBottomClose,
  "panel-bottom-dashed": PanelBottomDashed,
  "panel-bottom-open": PanelBottomOpen,
  "panel-left": PanelLeft,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  "panel-right": PanelRight,
  "panel-right-close": PanelRightClose,
  "panel-right-open": PanelRightOpen,
  paperclip: Paperclip,
  pen: Pen,
  "pen-line": PenLine,
  pencil: Pencil,
  pin: Pin,
  "pin-off": PinOff,
  plus: Plus,
  "plug-zap": PlugZap,
  quote: Quote,
  radar: Radar,
  "redo-2": Redo2,
  "refresh-ccw": RefreshCcw,
  "refresh-ccw-dot": RefreshCcwDot,
  regex: Regex,
  repeat: Repeat,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  route: Route,
  satellite: Satellite,
  scale: Scale,
  scan: Scan,
  "scan-document": FileSearch,
  "scan-eye": ScanEye,
  "scan-search": ScanSearch,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-x": ShieldX,
  shrink: Shrink,
  sigma: Sigma,
  signal: Signal,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  split: Split,
  spline: Spline,
  square: Square,
  "square-check": SquareCheck,
  "square-pen": SquarePen,
  "square-play": SquarePlay,
  "square-x": SquareX,
  stamp: Stamp,
  star: Star,
  "star-half": StarHalf,
  "star-off": StarOff,
  stethoscope: Stethoscope,
  sun: Sun,
  table: Table,
  tag: Tag,
  telescope: Telescope,
  terminal: Terminal,
  "text-select": TextSelect,
  timer: Timer,
  "tool-expand": Boxes,
  "tool-search": Search,
  "trash-2": Trash2,
  "undo-2": Undo2,
  "undo-dot": UndoDot,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  "user-round-pen": UserRoundPen,
  users: Users,
  waypoints: Waypoints,
  workflow: Workflow,
  "worktree-enter": GitFork,
  "worktree-leave": ArrowLeft,
  "worktree-list": LayoutGrid,
  wrench: Wrench,
  x: X,
  zap: Zap,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
}

export type IconName = keyof typeof icons | string

export interface IconProps extends Omit<ComponentProps<"svg">, "name"> {
  name: IconName
  size?: "small" | "normal" | "large"
  /** Override the icon color (applied as inline fill / stroke via `color`). */
  color?: string
}

export function Icon(props: IconProps) {
  const [local, others] = splitProps(props, ["name", "size", "class", "classList", "color"])

  // Check registry for a plugin-contributed icon with actual SVG markup
  const entry = () => getIcon(local.name)
  const pluginSvg = () => entry()?.svgContent

  // Fall back to Lucide component map for built-ins
  const Component = () => icons[local.name as keyof typeof icons]

  return (
    <div
      data-component="icon"
      data-size={local.size || "normal"}
      style={local.color ? { color: local.color } : undefined}
    >
      {(() => {
        const svg = pluginSvg()
        if (svg) {
          // Plugin icon: render raw SVG markup through innerHTML
          return (
            <span
              data-slot="icon-svg"
              class={local.class}
              classList={local.classList}
              // SVG content is sanitized during icon registration
              innerHTML={svg}
              style="width: 100%; height: 100%; display: inline-flex; align-items: center; justify-content: center;"
              {...(others as any)}
            />
          )
        }
        const lucide = Component()
        if (lucide) {
          return (
            <Dynamic
              component={lucide}
              data-slot="icon-svg"
              class={local.class}
              classList={local.classList}
              size="100%"
              strokeWidth={1.5}
              {...(others as any)}
            />
          )
        }
        // Neither plugin icon nor built-in — render nothing
        return null
      })()}
    </div>
  )
}

export { COMPUTER_TOOL_ICONS } from "./tool/computer-icons"
