// Product UI semantic icon token layer.
// Maps semantic token names to Lucide icon keys so that business components
// reference a token ("workspace.main") instead of a raw Lucide name ("folder").
// This gives us a single place to manage icon semantics and prevents the same
// Lucide icon being used for unrelated concepts.

import type { IconName } from "./icon"

export const SemanticIconToken = {
  // Product entities
  "holos.main": "satellite",
  "synergyLink.main": "plug-zap",
  "mcp.main": "cable",
  "lsp.main": "braces",
  "cortex.main": "workflow",
  "browser.main": "globe",
  "browser.screenshot": "image",
  "browser.inspect": "mouse-pointer-click",
  "browser.console": "chevrons-right",
  "browser.network": "spline",
  "browser.elements": "text-select",
  "browser.assets": "boxes",
  "browser.downloads": "book-down",
  "github.main": "github",
  "email.main": "mail",
  "channels.main": "message-circle",
  "plugins.main": "package",
  "plugins.permission.ui": "palette",
  "plugins.permission.tools": "list-todo",
  "plugins.permission.runtime": "gpu",
  "plugins.permission.hooks": "flask-conical",
  "plugins.permission.network": "share",
  "plugins.permission.data": "file-text",
  "plugins.permission.filesystem": "folder-plus",
  "plugins.permission.config": "settings",
  "plugins.permission.shell": "crosshair",
  "plugins.permission.hostUi": "building-2",
  "plugins.permission.diff": "diff",
  "workspace.main": "folder",
  "workspace.worktree": "git-fork",
  "workspace.enterWorktree": "worktree-enter",
  "workspace.leaveWorktree": "worktree-leave",
  "workspace.branch": "git-branch",
  "workspace.add": "folder-input",
  "workspace.identity": "fingerprint",
  "workspace.files": "folder-tree",
  "library.main": "book-open",
  "memory.main": "brain",
  "experience.main": "lightbulb",
  "agents.main": "users",
  "providers.main": "server",
  "providers.reconnect": "shield-alert",
  "agenda.main": "calendar-clock",
  "kanban.main": "kanban",
  "oryn.main": "megaphone",
  "terminal.main": "code",

  // Session runtime
  "session.default": "message-square",
  "session.new": "square-pen",
  "session.running": "loader-circle",
  "session.idle": "circle",
  "session.waiting": "hourglass",
  "session.retry": "rotate-ccw",
  "session.child": "arrow-down-from-line",
  "session.background": "calendar-days",
  "session.inbox": "inbox",
  "session.rewind": "undo-dot",
  "session.archive": "message-square-more",
  "session.context": "chart-pie",

  // Product domains
  "blueprint.main": "clipboard-list",
  "dag.main": "route",
  "holos.branch": "git-merge",
  "notes.main": "notebook-pen",
  "notes.create": "pen-line",
  "notes.search": "scan-search",
  "notes.folder": "folder-open",
  "notes.pin": "bookmark",
  "notes.archive": "archive",
  "notes.tag": "tag",
  "notes.select": "square-check",
  "notes.restore": "archive-restore",
  "performance.main": "radar",
  "performance.health": "heart-pulse",
  "performance.cpu": "circuit-board",
  "performance.memory": "memory-stick",
  "performance.issue": "badge-alert",
  "performance.timeline": "history",
  "performance.latency": "timer",
  "performance.trace": "activity",
  "performance.network": "network",
  "performance.disk": "database",
  "performance.frontend": "monitor-dot",
  "performance.routes": "map",
  "performance.sessions": "contact-round",
  "performance.tools": "wrench",
  "performance.providers": "cloud-upload",
  "performance.storage": "hard-drive",
  "performance.library": "book-marked",
  "performance.vitals": "circle-gauge",
  "performance.analysis": "binoculars",

  // Settings areas that are not product entities
  "settings.account": "user",
  "settings.general": "sliders-horizontal",
  "settings.colorSystem": "monitor",
  "settings.colorLight": "sun",
  "settings.colorDark": "moon",
  "settings.models": "cpu",
  "settings.usage": "gauge",
  "settings.learning": "graduation-cap",
  "settings.commands": "terminal",
  "settings.permissions": "shield-check",
  "settings.sandbox": "lock-keyhole",
  "settings.controlProfile": "scale",
  "settings.questions": "help-circle",
  "settings.compaction": "list-collapse",
  "settings.timeouts": "clock",
  "settings.formatter": "file-pen",
  "settings.observability": "stethoscope",
  "settings.diagnostics": "bug",
  "settings.import": "upload",
  "settings.configFiles": "folder-cog",
  "settings.personalize": "scroll-text",
  "settings.voice": "audio-lines",

  // Permission modes and prompts
  "permission.required": "octagon-alert",
  "permission.guarded": "badge-check",
  "permission.autonomous": "orbit",
  "permission.fullAccess": "shield-x",

  // App shell and window controls
  "app.sidebar": "panel-left",
  "app.sidebar.open": "panel-left-open",
  "app.sidebar.close": "panel-left-close",
  "app.sideWorkspace": "panel-right",
  "app.bottomSpace": "panel-bottom",
  "app.statusBar": "panel-bottom-dashed",
  "app.statusBar.toggle": "panel-bottom-open",
  "app.toolsDrawer": "layout-grid",
  "product.update": "download",
  "product.update.install": "rotate-cw",
  "window.minimize": "minus",
  "window.maximize": "square",
  "window.restore": "minimize-2",
  "window.close": "square-x",

  // Navigation
  "navigation.back": "arrow-left",
  "navigation.forward": "arrow-right",
  "navigation.expand": "chevron-right",
  "navigation.collapse": "chevron-down",
  "navigation.home": "home",

  // Prompt composer and command entry
  "prompt.attach": "paperclip",
  "prompt.plan": "list-checks",
  "prompt.lattice": "waypoints",
  "prompt.boss": "crown",
  "prompt.lightLoop": "repeat",
  "prompt.shell": "file-terminal",
  "prompt.signal": "signal",
  "prompt.submit": "corner-down-left",
  "prompt.send": "send",
  "prompt.submitArrow": "arrow-up",
  "prompt.blueprintStart": "circle-play",
  "prompt.blueprintEquip": "clipboard-check",
  "prompt.voice": "mic",

  // Quick actions and runtime commands
  "command.undo": "undo-2",
  "command.redo": "redo-2",
  "command.compact": "minimize",
  "command.init": "square-play",
  "command.review": "scan-eye",
  "command.commit": "git-commit-horizontal",
  "command.rmslop": "sparkles",
  "command.continue": "rocket",
  "command.audit": "microscope",
  "command.start": "zap",

  // Generic actions and state
  "action.pin": "pin",
  "action.unpin": "pin-off",
  "action.download": "download-cloud",
  "action.add": "plus",
  "action.grip": "grip",
  "action.clear": "circle-x",
  "action.close": "x",
  "action.copy": "copy",
  "action.fork": "split",
  "action.open": "arrow-up-right",
  "action.more": "ellipsis",
  "action.rename": "pencil",
  "action.export": "arrow-down-to-line",
  "action.external": "external-link",
  "action.import": "log-in",
  "action.archive": "file-archive",
  "action.info": "info",
  "action.search": "search",
  "action.remove": "trash-2",
  "action.refresh": "refresh-ccw",
  "action.restore": "refresh-ccw-dot",
  "action.view": "eye",
  "action.zoomOut": "zoom-out",
  "action.zoomIn": "zoom-in",
  "action.hide": "eye-off",
  "action.stop": "circle-stop",
  "account.create": "user-plus",
  "account.import": "key-round",
  "account.logout": "log-out",
  "state.success": "check",
  "state.empty": "circle-dashed",
  "state.warning": "alert-triangle",
  "state.error": "ban",
  "state.complete": "circle-check",
} as const satisfies Record<string, IconName>

export type SemanticIconTokenName = keyof typeof SemanticIconToken

export function getSemanticIcon(token: SemanticIconTokenName): IconName {
  return SemanticIconToken[token] as IconName
}
