import { validateSkinAssets } from "../lib/skin-assets.js"
import fs from "fs"
import path from "path"
import { pathToFileURL } from "url"
import type { Argv } from "yargs"
import {
  PluginArtifact,
  PluginManifest,
  isExecutableContributionKind,
  type PluginDefinition,
} from "@ericsanchezok/synergy-plugin"
import { cmd } from "../cmd.js"
import { UI } from "../ui.js"
import { sha256File } from "../lib/crypto.js"
import { loadPluginDefinition } from "../lib/definition.js"
import { validateThemeAssets } from "../lib/theme-assets.js"

export interface PluginValidationResult {
  type: "pass" | "warning" | "error"
  message: string
}

function executableIds(definition: PluginDefinition) {
  return definition.contributions
    .filter((item) => isExecutableContributionKind(item.kind))
    .map((item) => `${item.kind}:${item.id}`)
    .sort()
}

function trustedComponentSources(definition: PluginDefinition) {
  return definition.contributions.flatMap((item) => {
    if (item.kind === "ui.shell")
      return [item.component.source, ...Object.values(item.pages ?? {}).map((component) => component.source)]
    if (item.kind === "ui.textAction" && item.presentation) return [item.presentation.component.source]
    if (!item.kind.startsWith("ui.") || !("component" in item) || !item.component) return []
    return [item.component.source]
  })
}

async function runtimeHandlerIds(runtimePath: string, pluginId: string): Promise<string[]> {
  const url = pathToFileURL(runtimePath)
  url.searchParams.set("validate", String(Date.now()))
  const module = (await import(url.toString())) as Record<string, unknown>
  const definitions = [module.default, ...Object.values(module)].filter((value): value is PluginDefinition => {
    if (!value || typeof value !== "object" || Array.isArray(value)) return false
    const record = value as Record<string, unknown>
    return record.id === pluginId && Array.isArray(record.handlerIds)
  })
  if (definitions.length === 0) throw new Error(`Runtime does not export definePlugin() definition for ${pluginId}`)
  return [...definitions[0]!.handlerIds].sort()
}

export async function validatePluginProject(
  pluginDir: string,
  options: { runtimeDiscovery?: boolean } = {},
): Promise<PluginValidationResult[]> {
  const results: PluginValidationResult[] = []
  try {
    if (fs.existsSync(path.join(pluginDir, "plugin.json"))) {
      results.push({ type: "error", message: "Source plugin.json is not allowed; the manifest is generated by build" })
    }
    const { definition } = await loadPluginDefinition(pluginDir)
    results.push({ type: "pass", message: `definePlugin() descriptor valid: ${definition.id}@${definition.version}` })
    expectEqual(definition.handlerIds.slice().sort(), executableIds(definition), "descriptor handler ids", results)
    validateSkinAssets(pluginDir, definition.contributions)
    for (const asset of validateThemeAssets(pluginDir, definition.contributions)) {
      results.push({ type: "pass", message: `source theme valid: ${asset.contribution.id}` })
    }

    for (const source of trustedComponentSources(definition)) {
      if (fs.existsSync(path.resolve(pluginDir, source))) {
        results.push({ type: "pass", message: `trusted UI source exists: ${source}` })
      } else {
        results.push({ type: "error", message: `trusted UI source is missing: ${source}` })
      }
    }

    const manifestPath = path.join(pluginDir, "dist", PluginArtifact.manifestFile)
    if (!fs.existsSync(manifestPath)) {
      results.push({ type: "warning", message: "dist/plugin.json not found; run build to validate packaged artifacts" })
      return results
    }
    const manifest = PluginManifest.parse(JSON.parse(fs.readFileSync(manifestPath, "utf-8")))
    for (const item of manifest.contributions) {
      if (item.kind !== "ui.skin") continue
      verifyArtifact(pluginDir, item.path, item.sha256, "Skin", results)
      for (const asset of item.assets) verifyArtifact(pluginDir, asset.entry, asset.sha256, "Skin resource", results)
    }
    results.push({ type: "pass", message: "generated manifest schema valid" })
    if (manifest.id !== definition.id || manifest.version !== definition.version) {
      results.push({ type: "error", message: "generated manifest identity does not match definePlugin()" })
    }
    const runtime = manifest.artifacts.runtime
    const ui = manifest.artifacts.ui
    if (runtime) verifyArtifact(pluginDir, runtime.entry, runtime.sha256, "runtime", results)
    if (ui) verifyArtifact(pluginDir, ui.entry, ui.sha256, "UI", results)
    for (const resource of ui?.resources ?? []) {
      verifyArtifact(pluginDir, resource.entry, resource.sha256, `UI resource ${resource.entry}`, results)
    }
    validateSkinAssets(path.join(pluginDir, "dist"), manifest.contributions)
    for (const asset of validateThemeAssets(path.join(pluginDir, "dist"), manifest.contributions)) {
      results.push({ type: "pass", message: `packaged theme valid: ${asset.contribution.id}` })
    }

    if (options.runtimeDiscovery && runtime) {
      const discovered = await runtimeHandlerIds(path.join(pluginDir, "dist", runtime.entry), manifest.id)
      const declared = manifest.contributions
        .filter((item) => isExecutableContributionKind(item.kind))
        .map((item) => `${item.kind}:${item.id}`)
        .sort()
      expectEqual(discovered, declared, "runtime handlers", results)
    }
  } catch (error) {
    results.push({ type: "error", message: error instanceof Error ? error.message : String(error) })
  }
  return results
}

function verifyArtifact(
  pluginDir: string,
  entry: string,
  expectedHash: string,
  label: string,
  results: PluginValidationResult[],
) {
  const artifact = path.join(pluginDir, "dist", entry)
  if (!fs.existsSync(artifact)) {
    results.push({ type: "error", message: `${label} artifact is missing: ${entry}` })
    return
  }
  if (sha256File(artifact) !== expectedHash) {
    results.push({ type: "error", message: `${label} artifact hash does not match generated manifest` })
    return
  }
  results.push({ type: "pass", message: `${label} artifact integrity valid` })
}

function expectEqual(actual: string[], expected: string[], label: string, results: PluginValidationResult[]) {
  if (JSON.stringify(actual) === JSON.stringify(expected)) {
    results.push({ type: "pass", message: `${label} match generated contributions` })
    return
  }
  results.push({
    type: "error",
    message: `${label} mismatch: expected [${expected.join(", ")}], received [${actual.join(", ")}]`,
  })
}

function printResults(results: PluginValidationResult[]) {
  for (const result of results) {
    const prefix = result.type === "pass" ? "PASS" : result.type === "warning" ? "WARN" : "ERROR"
    UI.println(`${prefix} ${result.message}`)
  }
}

export const PluginValidateCommand = cmd({
  command: "validate [path]",
  describe: "validate definePlugin() source and generated artifacts",
  builder: (yargs: Argv) =>
    yargs
      .positional("path", { type: "string", describe: "plugin directory (defaults to cwd)" })
      .option("runtime-discovery", { type: "boolean", default: false, describe: "verify packaged runtime handlers" }),
  async handler(args) {
    const results = await validatePluginProject(path.resolve((args.path as string) ?? process.cwd()), {
      runtimeDiscovery: Boolean(args["runtime-discovery"]),
    })
    printResults(results)
    if (results.some((result) => result.type === "error")) process.exitCode = 1
  },
})
