import fs from "node:fs"
import path from "node:path"
import { compile } from "json-schema-to-typescript"
import { format } from "prettier/standalone"
import babel from "prettier/plugins/babel"
import estree from "prettier/plugins/estree"
import { schemaToJsonSchema, type PluginDefinition } from "@ericsanchezok/synergy-plugin"
import { loadPluginDefinition } from "./definition.js"

const banner = "// Generated by synergy-plugin typegen. Do not edit.\n"

export async function renderPluginDataTypes(definition: PluginDefinition) {
  const files = new Map<string, string>()
  const queries: string[] = []
  const commands: string[] = []
  const events: string[] = []
  // Preserve JSON Schema semantics through the upstream compiler rather than
  // maintaining a second schema language: https://github.com/bcherny/json-schema-to-typescript
  const convert = async (schema: Parameters<typeof schemaToJsonSchema>[0], file: string) => {
    files.set(
      `${file}.d.ts`,
      await compile(schemaToJsonSchema(schema), "Value", {
        bannerComment: banner.trimEnd(),
        unknownAny: true,
        $refOptions: { resolve: { file: false, http: false } },
        format: false,
      }),
    )
    return `import(${JSON.stringify(`./${file}.js`)}).Value`
  }
  await Promise.all(
    definition.contributions.map(async (item) => {
      if (item.kind === "operation" && item.expose.includes("ui")) {
        const [input, output] = await Promise.all([
          convert(item.input, `operation.${item.id}.input`),
          convert(item.output, `operation.${item.id}.output`),
        ])
        const entry = `  ${JSON.stringify(item.id)}: { input: ${input}; output: ${output} }`
        ;(item.type === "query" ? queries : commands).push(entry)
      }
      if (item.kind === "event")
        events.push(`  ${JSON.stringify(item.id)}: ${await convert(item.payload, `event.${item.id}`)}`)
    }),
  )
  files.set(
    "index.d.ts",
    `${banner}import type { PluginSurfaceContext, PluginUIEventMetadata } from "@ericsanchezok/synergy-plugin"

export interface Queries {
${queries.sort().join("\n")}
}
export interface Commands {
${commands.sort().join("\n")}
}
export interface Events {
${events.sort().join("\n")}
}
export type PluginDataContext<C extends PluginSurfaceContext = PluginSurfaceContext> = Omit<C, "operations" | "events"> & {
  operations: {
    query<Id extends keyof Queries>(id: Id, input: Queries[Id]["input"], options?: { signal?: AbortSignal }): Promise<Queries[Id]["output"]>
    command<Id extends keyof Commands>(id: Id, input: Commands[Id]["input"], options?: { signal?: AbortSignal }): Promise<Commands[Id]["output"]>
  }
  events: {
    subscribe<Id extends keyof Events>(id: Id, listener: (payload: Events[Id], metadata: PluginUIEventMetadata) => void): () => void
  }
}
`,
  )
  await Promise.all(
    [...files].map(async ([name, source]) => {
      files.set(
        name,
        await format(source, { parser: "babel-ts", plugins: [babel, estree], semi: false, printWidth: 120 }),
      )
    }),
  )
  return files
}

export async function generatePluginDataTypes(pluginDir: string, definition?: PluginDefinition) {
  const files = await renderPluginDataTypes(definition ?? (await loadPluginDefinition(pluginDir)).definition)
  const directory = path.join(pluginDir, "src/generated/plugin-data")
  fs.mkdirSync(directory, { recursive: true })
  for (const [name, source] of files) {
    const target = path.join(directory, name)
    if (fs.existsSync(target) && fs.readFileSync(target, "utf8") === source) continue
    const temporary = `${target}.tmp`
    fs.writeFileSync(temporary, source)
    fs.renameSync(temporary, target)
  }
  for (const file of fs.readdirSync(directory)) {
    if (files.has(file) || !file.endsWith(".d.ts")) continue
    const target = path.join(directory, file)
    if (fs.readFileSync(target, "utf8").startsWith(banner.trimEnd())) fs.unlinkSync(target)
  }
  return directory
}
